<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8" />';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0" />';
echo '<title>EasyTravel</title>';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"';
echo '/>';
echo '<link rel="stylesheet" href="css/style.css" />';
echo '<link rel="stylesheet" href="css/responsive.css" />';
echo '<link';
echo 'rel="apple-touch-icon"';
echo 'sizes="180x180"';
echo 'href="img/apple-touch-icon.png"';
echo '/>';
echo '<link';
echo 'rel="icon"';
echo 'type="image/png"';
echo 'sizes="32x32"';
echo 'href="img/favicon-32x32.png"';
echo '/>';
echo '<link';
echo 'rel="icon"';
echo 'type="image/png"';
echo 'sizes="16x16"';
echo 'href="img/favicon-16x16.png"';
echo '/>';
echo '<link rel="manifest" href="/site.webmanifest" />';
echo '</head>';
echo '<body';
echo 'onload='if (window.location.href.substr(window.location.href.length - 6) == "#about") { introAboutLogoTransition(); }'';
echo '>';
echo '<!--navbar-->';
echo '<nav class="navbar glass" style="height: 70px">';
echo '<span';
echo '><a href="#home" style="display: flex; align-items: center"';
echo '><img';
echo 'class="img2"';
echo 'src="./img/mountain.png"';
echo 'width="40"';
echo 'style="margin: -25px -10px -25px -20px"';
echo '/>';
echo '<h1 class="logo">&nbsp;EasyTravel</h1></a';
echo '></span';
echo '>';
echo '<ul class="nav-links">';
echo '<li>';
echo '<a href="#home" id="pri" class="active cir_border">Home</a>';
echo '</li>';
echo '<li><a href="#events" id="sec" class="cir_border">Events</a></li>';
echo '<li>';
echo '<a href="#explore" id="tri" class="cir_border">Explore</a>';
echo '</li>';
echo '<li>';
echo '<a href="#tours" id="quad" class="cir_border">Tours</a>';
echo '</li>';
echo '<li><a href="#about" id="quint" class="cir_border">About</a></li>';
echo '';
echo '<li>';
echo '<a href="#contact" id="hept" class="cir_border">Contact</a>';
echo '</li>';
echo '<li>';
echo '<div>';
echo '<input';
echo 'type="checkbox"';
echo 'class="checkbox dark"';
echo 'id="checkbox"';
echo '/>';
echo '<label for="checkbox" class="label">';
echo '<i class="fa fa-moon-o"></i>';
echo '<i class="fa fa-sun-o"></i>';
echo '<div class="ball"></div>';
echo '</label>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '<img src="./img/menu-btn.png" alt="" class="menu-btn" />';
echo '</nav>';
echo '<!--navbar-->';
echo '';
echo '<header id="home">';
echo '<div class="header-content">';
echo '<h2 id="quote">Explore the colourful World</h2>';
echo '<div class="line"></div>';
echo '<h1>A WONDERFUL GIFT</h1>';
echo '<a';
echo 'href="#about"';
echo 'class="ctn"';
echo 'onclick='removeall(); $("#quad").css("border", "2px solid whitesmoke"); $("#quad").css("border-radius", "20px");'';
echo '>Learn more</a';
echo '>';
echo '</div>';
echo '</header>';
echo '';
echo '<!--Events-->';
echo '<section class="events" id="events">';
echo '<div class="container">';
echo '<div class="title">';
echo '<h1 class="dark">Upcoming Events</h1>';
echo '<div class="line"></div>';
echo '</div>';
echo '<div class="row">';
echo '<article class="card col">';
echo '<img class="card-img" src="./img/img1.jfif" />';
echo '<h4 class="dark">Everest camp trek</h4>';
echo '<p class="font-color">';
echo 'Everest base camp trek is without a doubt, one of';
echo 'the most renowned travel destinations in the world.';
echo '</p>';
echo '<a href="#" class="ctn">All Details</a>';
echo '</article>';
echo '<article class="card col">';
echo '<img src="./img/img2.jfif" />';
echo '<h4 class="dark">Walking holidays</h4>';
echo '<p class="font-color">';
echo 'Join small guided group walks, enjoy a challenging';
echo 'trek, or a luxury private guided walk which can be';
echo 'made especially for you.';
echo '</p>';
echo '<a href="#" class="ctn">All Details</a>';
echo '</article>';
echo '<article class="card col">';
echo '<img src="./img/img2.jfif" />';
echo '<h4 class="dark">Andaman Beaches</h4>';
echo '<p class="font-color">';
echo 'Diving in Andaman Beaches is exceptional. The costal';
echo 'belt surroundings is one of the richest coral reef';
echo 'ecosystems in the world.';
echo '</p>';
echo '<a href="#" class="ctn">All Details</a>';
echo '</article>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!--Events-->';
echo '';
echo '<!--Explore-->';
echo '<section class="explore" id="explore">';
echo '<div class="explore-content">';
echo '<h1>EXPLORE THE WORLD</h1>';
echo '<div class="line"></div>';
echo '<p>';
echo '“Travel makes one modest. You see what a tiny place you';
echo 'occupy in the world.”– Gustav Flaubert <br />Exploring will';
echo 'make you want to pack your bag, book that ticket and jet';
echo 'away.';
echo '</p>';
echo '<a href="#" class="ctn">Explore more</a>';
echo '</div>';
echo '</section>';
echo '<!--Explore-->';
echo '';
echo '<!--tours-->';
echo '<section class="tours" id="tours">';
echo '<div class="container row">';
echo '<div class="col content-col">';
echo '<h1 class="font-color">UPCOMING TOURS & DESTINATION</h1>';
echo '<div class="line"></div>';
echo '<p>';
echo 'Wed 28 sept 2023 : Port of Spain City Tour and Birdseye';
echo 'Fort View. <br />';
echo 'Sat 1 oct 2023 : Tour the Gasparee Caves.<br />';
echo 'Tues 4 oct 2023 : Trinidad North Coast Experience.';
echo '<br />';
echo 'and many more ......';
echo '</p>';
echo '<a href="#" class="ctn">Learn more</a>';
echo '</div>';
echo '<div class="image-col">';
echo '<div class="image-gallery">';
echo '<img src="./img/img3.png" alt="" />';
echo '<img src="./img/img4.png" alt="" />';
echo '<img src="./img/img5.png" alt="" />';
echo '<img src="./img/img6.png" alt="" />';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<br /><br /><br /><br />';
echo '</section>';
echo '<!--tours-->';
echo '';
echo '<!-- About -->';
echo '<section id="about">';
echo '<div class="title">';
echo '<h1 class="font-color">About Us</h1>';
echo '<div class="line"></div>';
echo '</div>';
echo '<br />';
echo '<div id="about_us">';
echo '<div class="boxx">';
echo '<div class="containerx">';
echo '<input type="radio" name="slider" id="item-1" checked />';
echo '<input type="radio" name="slider" id="item-2" />';
echo '<input type="radio" name="slider" id="item-3" />';
echo '<div class="cards">';
echo '<label class="cardt" for="item-1" id="col-img-1">';
echo '<img src="./img/carousel-img4.jpg" />';
echo '</label>';
echo '<label class="cardt" for="item-2" id="col-img-2">';
echo '<img src="./img/carousel-img5.jpg" />';
echo '</label>';
echo '<label class="cardt" for="item-3" id="col-img-3">';
echo '<img src="./img/carousel-img6.jpg" />';
echo '</label>';
echo '';
echo '</div>';
echo '</div>';
echo '<span id="about-quad"';
echo '><a href="#home"';
echo '><center>';
echo '<h1';
echo 'style="';
echo 'font-family: var(--ff-montserrat);';
echo 'color: white;';
echo '"';
echo '>';
echo 'Find that';
echo '</h1>';
echo '<br />';
echo '<img';
echo 'class="img2"';
echo 'src="./img/mountain_dark.jpg"';
echo 'width="200"';
echo 'style="border-radius: 12%"';
echo '/>';
echo '<br />';
echo '<h1 class="logo" style="font-size: 50px">';
echo 'EasyTravel';
echo '</h1>';
echo '</center>';
echo '</a>';
echo '</span>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '';
echo '<!-- contact -->';
echo '<section id="contact">';
echo '<div class="title">';
echo '<h1 class="font-color">Contact Us</h1>';
echo '<div class="line"></div>';
echo '</div>';
echo '<div class="contact_us">';
echo '<form class="cform" action="" method="post">';
echo '<div class="crow-message">';
echo '<h1 class="color">Send us a message</h1>';
echo '<div></div>';
echo '</div>';
echo '<div class="crow-in">';
echo '<input';
echo 'type="text"';
echo 'id="name"';
echo 'name="name"';
echo 'placeholder="Your name"';
echo '/>';
echo '<input';
echo 'type="text"';
echo 'id="email"';
echo 'name="email"';
echo 'placeholder="Your Email id"';
echo '/>';
echo '</div>';
echo '<div class="crow">';
echo '<div class="ccol-left">';
echo '<select name="country" id="country">';
echo '<option value="India">India</option>';
echo '<option value="Russia">Russia</option>';
echo '<option value="usa">USA</option>';
echo '<option value="Japan">Japan</option>';
echo '<option value="France">France</option>';
echo '<option value="Brazil">Brazil</option>';
echo '</select>';
echo '</div>';
echo '</div>';
echo '<div class="crow">';
echo '<div class="ccol-left">';
echo '<textarea';
echo 'type="text"';
echo 'id="remarks"';
echo 'name="remarks"';
echo 'placeholder="Your Remarks....."';
echo 'style="height: 150px"';
echo '></textarea>';
echo '</div>';
echo '</div>';
echo '<input class="crow-s" type="submit" value="Submit" />';
echo '</form>';
echo '<div class="cbox">';
echo '<div>';
echo '<p class="cbox-message">';
echo 'Prefer some other way ?<br />Reach us by using the';
echo 'details given below';
echo '</p>';
echo '<div class="cbox-line"></div>';
echo '</div>';
echo '<div class="c_boxx">';
echo '<a href="mailto:abc@gmail.com"';
echo '><i class="fa fa-envelope"></i>';
echo 'Mail: tourism@EasyTravel.com';
echo '</a>';
echo '</div>';
echo '<div class="c_boxx">';
echo '<a href="tel:+91-12345-67890"';
echo '><i class="fa fa-phone"></i>';
echo 'Phone: (+91) 12345-67890';
echo '</a>';
echo '</div>';
echo '<div class="c_boxx">';
echo '<a href="#"';
echo '><i class="fa fa-map-marker"></i>';
echo 'Location: Mumbai,Maharashtra,India';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- contact  -->';
echo '<!-- up scroll -->';
echo '<i class="arrow"  onclick="topFunction()" id="upbtn"></i>';
echo '<!-- end -->';
echo '<!--footer-->';
echo '<section class="footer">';
echo '<span';
echo '>Created By Team EasyTravel | &#169; 2022 All rights';
echo 'reserved.</span';
echo '>';
echo '<div class="social">';
echo '<li>';
echo '<a';
echo 'href="https://easy-travel-rouge.vercel.app"';
echo 'target="_blank"';
echo 'rel="noreferrer"';
echo '><i class="fa fa-globe"></i';
echo '></a>';
echo '<a';
echo 'href="https://github.com/Mohitkanyal"';
echo 'target="_blank"';
echo 'rel="noreferrer"';
echo '><i class="fa fa-github"></i';
echo '></a>';
echo '<a';
echo 'href="https://www.linkedin.com/in/mohit-kanyal-33489622a/"';
echo 'target="_blank"';
echo 'rel="noreferrer"';
echo '><i class="fa fa-linkedin-square"></i';
echo '></a>';
echo '</li>';
echo '</div>';
echo '</section>';
echo '<!--footer-->';
echo '';
echo '<script>';
echo 'const menuBtn = document.querySelector(".menu-btn");';
echo 'const navlinks = document.querySelector(".nav-links");';
echo '';
echo 'menuBtn.addEventListener("click", () => {';
echo 'navlinks.classList.toggle("mobile-menu");';
echo '});';
echo '</script>';
echo '<script src="https://code.jquery.com/jquery-3.6.0.js"></script>';
echo '<script src="js/script.js"></script>';
echo '</body>';
echo '</html>';
?>
